baseURL: "https://jdmillstein.github.io/" 
title: Joanna Millstein
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

    
menu:
    main:
        - name: Research
          url: research/
          weight: 1
        - name: Travels
          url: travels/
          weight: 2
        - name: CryoCloud
          url: "https://cryointhecloud.com/"
          weight: 3

params:
    description: "Using Satellite Data to Decipher Earth Systems"
    #author: Joanna Millstein
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research","travels","CryoCloud"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Joanna D. Millstein
          subtitle: "I am a Postdoctoral Fellow in Geophysics at the Colorado School of Mines. Recently, I recieved my PhD in Geophysics from the MIT-WHOI Joint Program in Oceanography and Engineering with a dissertation entitled <i>The Flow and Fracture of Antarctic Ice Shelves</i>. <br><br> 
          I'm a geophysical glaciologist interested in the movement, stability, and fracture of glacier ice. My research is motivated to resolve the nonlinear physics of glacier ice to better understand future global climate change. I use observational data, from satellites and measurements in the field, to derive mechanical and statistical models for glacier ice processes."
          imageUrl: "headshot.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: research/
            - name: Travels
              url: travels/
            - name: CryoCloud
              url: "https://cryointhecloud.com/"
    socialIcons:
        - name: CV
          url: millstein_cv.pdf
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=NL6GZekAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/jdmillstein
        - name: Linkedin
          url: https://www.linkedin.com/in/jdmillstein17/


    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Joanna Millstein"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
