baseURL: "https://jdmillstein.github.io/" 
title: Joanna Millstein
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

    
menu:
    main:
        - name: Research
          url: research/
          weight: 1
        - name: Travels
          url: travels/
          weight: 2
        - name: CryoCloud
          url: "https://cryointhecloud.com/"
          weight: 3

params:
    description: "Earth, risk, resilience"
    #author: Joanna Millstein
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research","travels","CryoCloud"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    css:
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Joanna D. Millstein
          subtitle: "I am a Senior Earth Scientist at <a href='https://www.earthfinance.com/' target='_blank' rel='noopener noreferrer'>Earth Finance</a>, developing tools to accelerate an economic transition to a sustainable future. I am interested in the relationship between physical and financial risk. Previously, I was a Postdoctoral Fellow in Geophysics at the Colorado School of Mines and received my PhD in Geophysics from the Massachusetts Institute of Technology, as a member of the MIT-WHOI Joint Program in Oceanography and Engineering. My dissertation is entitled <i>The Flow and Fracture of Antarctic Ice Shelves</i>. <br><br>
          I am a climate geophysicist working at the intersection of remote sensing, physics, and data-driven modeling to understand the deformation of the ground beneath our feet and extreme climate scenarios. I'm interested in advancing solutions for climate adaptation and resilience through rigorously tested science and creative collaborations."
          imageUrl: "headshot.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: research/
            - name: Travels
              url: travels/
            - name: CryoCloud
              url: "https://cryointhecloud.com/"
    socialIcons:
        - name: CV
          url: millstein_cv.pdf
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=NL6GZekAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/jdmillstein
        - name: Linkedin
          url: https://www.linkedin.com/in/jdmillstein17/
        - name: Substack
          url: https://substack.com/@risingseas


    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Joanna Millstein"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
